data = [
    {"name": "Instagram", "follower_count": 346},
    {"name": "Cristiano Ronaldo", "follower_count": 215},
    {"name": "Ariana Grande", "follower_count": 183},
    {"name": "Dwayne Johnson", "follower_count": 181},
    {"name": "Kylie Jenner", "follower_count": 179},
    {"name": "Selena Gomez", "follower_count": 174},
    {"name": "Kim Kardashian", "follower_count": 167},
    {"name": "Lionel Messi", "follower_count": 149},
    {"name": "Beyonce", "follower_count": 145},
    {"name": "Neymar", "follower_count": 138},
    {"name": "Taylor Swift", "follower_count": 131},
    {"name": "Kendall Jenner", "follower_count": 127},
    {"name": "Jennifer Lopez", "follower_count": 119},
    {"name": "Nicki Minaj", "follower_count": 113},
    {"name": "National Geographic", "follower_count": 98},
    {"name": "Nike", "follower_count": 86},
    {"name": "Khloe Kardashian", "follower_count": 86},
    {"name": "Miley Cyrus", "follower_count": 85},
    {"name": "Katy Perry", "follower_count": 85},
    {"name": "Kourtney Kardashian", "follower_count": 79},
    {"name": "Kevin Hart", "follower_count": 73},
    {"name": "Ellen DeGeneres", "follower_count": 71},
    {"name": "Real Madrid", "follower_count": 70},
    {"name": "FC Barcelona", "follower_count": 67},
    {"name": "Zendaya", "follower_count": 66},
        ]